import { productAvailability } from "@/data/availability";
import { PageSchema } from "@/components/seo/PageSchema";
import { ArrowIcon } from "@/components/ui/ArrowIcon";
import Link from "next/link";
import { Illustration } from "@/components/guide/Illustration";
import { models } from "@/data/models";
import { PageIntro, SystemMap } from "@/components/guide/Visuals";
import { pageMetadata } from "@/lib/site";
export const metadata=pageMetadata("/explore");
export default function ExplorePage(){return <main id="main" className="guide container-wide"><PageSchema path="/explore"/><PageIntro title="Explore Muse">One family. Different ways to think, create and get things done.</PageIntro><section className="platform-overview"><div><h2>The whole picture.</h2><p>Muse brings models, software and tools together in one experience. Start with the platform, or explore a part of it below.</p><Link className="text-link" href="/explore/muse">What is Muse? <ArrowIcon/></Link></div><SystemMap/></section><section className="guide-section"><h2>Core AI</h2>{models.slice(0,2).map(m=><article className={`feature-row feature-${m.slug}`} key={m.slug}><div><h3>{m.shortName}</h3>{productAvailability[m.slug] && <span className="availability-label">{productAvailability[m.slug]}</span>}<p>{m.purpose}</p><p className="feature-fact">{m.kind==="hosted"?"Runs in the cloud":"Runs on your hardware"}</p><Link className="text-link" href={`/explore/${m.slug}`}>Explore {m.shortName} <ArrowIcon/></Link></div><Illustration id={`product-${m.slug}`} alt={`Concept: ${m.name}`}/></article>)}</section><section className="guide-section"><h2>Create with media</h2><div className="media-grid">{models.slice(2).map(m=><Link className="media-tile" href={`/explore/${m.slug}`} key={m.slug}><Illustration id={`product-${m.slug}`} alt={`Concept: ${m.name}`}/><h3>{m.shortName}</h3>{productAvailability[m.slug] && <span className="availability-label">{productAvailability[m.slug]}</span>}<p>{m.purpose}</p><span className="text-link">Explore {m.shortName} <ArrowIcon/></span></Link>)}</div></section><section className="guide-section"><h2>Software for doing the work</h2><div className="feature-row"><div><h3>Muse Code</h3><p>Understand a codebase, change files, run development tools and check the result.</p><Link className="text-link" href="/explore/code">Explore Muse Code <ArrowIcon/></Link></div><Illustration id="product-code" alt="Concept: editor, repository and checks"/></div></section></main>;}
