"use client";

import { ArrowIcon } from "@/components/ui/ArrowIcon";


import { useRef, useState } from "react";

type Source = { label: string; href: string };

export function FooterLinks({ sources }: { sources: Source[] }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [view, setView] = useState<"resources" | "about">("resources");

  function open(view: "resources" | "about") {
    setView(view);
    dialog.current?.showModal();
  }

  return <div>
      <button className="footer-link" onClick={() => open("resources")}>Official Meta resources <ArrowIcon/></button>
      <button className="footer-link" onClick={() => open("about")}>About sources <ArrowIcon/></button>
    <dialog ref={dialog} className="source-drawer" aria-labelledby="footer-source-title" onClick={event => { if (event.target === event.currentTarget) dialog.current?.close(); }}>
      <div className="drawer-content">
        <div className="drawer-heading"><h2 id="footer-source-title">{view === "resources" ? "Official Meta resources" : "About sources"}</h2><button onClick={() => dialog.current?.close()} aria-label="Close sources">×</button></div>
        {view === "resources" ? <ol>{sources.map(source => <li key={source.href}><a href={source.href} target="_blank" rel="noreferrer">{source.label} <ArrowIcon direction="external"/></a></li>)}</ol> : <>
          <p>This guide uses official documentation, announcements and examples. Availability and specifications can change; consult the original material before relying on them.</p>
          <p>Example screenshots come from the Meta cookbooks. Scenarios are illustrative. Generated artwork was created for this guide with ChatGPT and does not depict official Muse interfaces or claim to be generated by Muse.</p>
        </>}
      </div>
    </dialog>
  </div>;
}
