import { PageSchema } from "@/components/seo/PageSchema";
import { ArrowIcon } from "@/components/ui/ArrowIcon";
import Link from "next/link";
import type { MuseModel } from "@/data/models";
import { productGuide } from "@/data/product-guide";
import { productAvailability } from "@/data/availability";
import { projects } from "@/data/projects";
import { productStories } from "@/data/product-stories";
import { PageIntro, ExampleCard, FactRow, Process } from "@/components/guide/Visuals";
import { Illustration } from "@/components/guide/Illustration";
import { ProductDemo } from "@/components/guide/ProductDemo";
import { Architecture } from "@/components/guide/Architecture";
export function ModelDetail({ model }: { model: MuseModel }) {
  const story=productStories[model.slug];
  const guide = productGuide[model.slug];
  const related = guide.examples.flatMap(slug => {
    const example = projects.find(project => project.slug === slug);
    return example ? [example] : [];
  });
  return <main id="main" className={`guide product-experience product-${model.slug} container-wide`}><PageSchema path={`/explore/${model.slug}`} name={model.name}/>
    <Link className="back-link" href="/explore"><ArrowIcon direction="left"/> Explore Muse</Link>
    <div className="product-hero"><div>{productAvailability[model.slug] && <span className="availability-label">{productAvailability[model.slug]}</span>}<PageIntro title={model.name}>{story.headline}</PageIntro>{model.slug==="video"&&<p className="availability-note">Preview / roadmap in the source material. This is not a live video-generation tool.</p>}</div><Illustration id={`product-${model.slug}`} alt={`Concept illustration of ${model.name}`} priority/></div>
    <section className="product-definition"><h2>{model.slug==="glimmer"?"Your environment. Your configuration.":model.slug==="voice"?"Speech in. Text out.":model.slug==="image"?"Create, inspect, refine.":`Meet ${model.shortName}.`}</h2><p>{model.summary}</p></section>
    <section className="guide-section"><h2>What {model.shortName} is good at</h2><div className={`ability-grid abilities-${model.slug}`}>{story.abilities.map((a,i)=><article key={a.title}><div className={`ability-glyph glyph-${i}`} aria-hidden="true"><i/><i/><i/></div><h3>{a.title}</h3><p>{a.detail}</p></article>)}</div></section>
    <section className="guide-section"><div className="section-heading"><div><h2>{story.scenario}</h2><p className="section-lede">{story.task}</p></div><span className="concept-label">Illustrative scenario</span></div><ProductDemo kind={model.slug}/></section>
    {model.slug==="glimmer"&&<section className="guide-section"><h2>What hardware do you need?</h2><p className="section-lede">Start with the model variant and runtime. Memory must hold the model weights and working context; longer inputs and concurrent tasks need more headroom. Quantization stores model values at lower precision to use less memory, with tradeoffs in quality and speed.</p><div className="related-links"><div><h3>Memory</h3><p>Check the runtime’s requirements for your chosen model and context length before downloading.</p></div><div><h3>Compute</h3><p>Supported acceleration and available memory affect how quickly the model responds.</p></div><div><h3>Offline readiness</h3><p>Download the model and dependencies first. Check whether any configured tools still need the network.</p></div></div></section>}
    <section className="guide-section product-fit"><h2>Where it fits in Muse</h2>{model.slug==="spark"||model.slug==="glimmer"?<div className="comparison-table"><table><caption>Spark and Glimmer at a glance</caption><thead><tr><th scope="col">Consideration</th><th scope="col">{model.slug === "spark" ? "Spark" : <Link href="/explore/spark">Spark <ArrowIcon/></Link>}</th><th scope="col">{model.slug === "glimmer" ? "Glimmer" : <Link href="/explore/glimmer">Glimmer <ArrowIcon/></Link>}</th></tr></thead><tbody><tr><th scope="row">Runs</th><td>Hosted service</td><td>Your hardware</td></tr><tr><th scope="row">Typical fit</th><td>Complex reasoning and tool-based work</td><td>Local files and self-managed workflows</td></tr><tr><th scope="row">You provide</th><td>Context, tools and permissions</td><td>Hardware, runtime, tools and controls</td></tr><tr><th scope="row">Tradeoff</th><td>Data handling depends on the hosted service</td><td>Hardware needs and capability limits</td></tr></tbody></table></div>:<div className="fit-explanation"><p>{model.slug==="code"?"Code is the software around the model: repository access, commands and a development workflow. Spark supplies the reasoning; you review the resulting changes.":model.slug==="muse"?"Muse is the connected experience. Models provide intelligence, tools make work possible, and permissions set the boundaries around actions.":model.slug==="voice"?"Voice Transcribe turns audio into text. Spark or your application can interpret that text and choose an action. Voice Transcribe itself does not generate speech.":model.slug==="image"?"Image creates and edits visuals. Spark can help reason about a brief or inspect inputs; the application manages the generation and editing workflow.":"Video belongs to the media family. Its announced direction differs from the established request-and-response workflows described for Spark, Image and Voice."}</p></div>}{guide.related.length > 0 && <div className="related-links">{guide.related.map(link => <Link key={link.href} href={link.href}><h3>{link.title} <ArrowIcon/></h3><p>{link.description}</p></Link>)}</div>}</section>
    <section className="guide-section"><h2>{related.length?(model.slug === "code" ? "Muse Code examples" : "Real examples"):"Explore further"}</h2>{related.length?<div className={`example-grid ${related.length<3?"two":""}`}>{related.map(p=><ExampleCard key={p.slug} project={p}/>)}</div>:<div className="example-context"><p>{model.slug==="video"?"Video is presented as a preview in this guide. Check the announcement and availability limits before planning around it.":"This guide does not yet include a dedicated example for this product. Start with a task to see how the workflow could fit your needs."}</p><Link className="text-link" href={guide.task.href}>{guide.task.label} <ArrowIcon/></Link></div>}</section>
    <section className="guide-section"><h2>Technical architecture</h2><p className="section-lede">{model.howItWorks}</p>{["spark","glimmer","muse","code"].includes(model.slug)?<Architecture local={model.slug==="glimmer"}/>:<div className="product-flow"><Process steps={story.flow}/></div>}</section>
    <section id="specifications" className="visible-specs"><h2>Specifications and limitations</h2><div className="spec-columns"><dl>{model.specs.map(s=><FactRow key={s.label} label={s.label}>{s.value}</FactRow>)}</dl><div><h3>Keep in mind</h3><ul className="plain-list">{model.limitations.map(l=><li key={l}>{l}</li>)}</ul></div></div></section>
    <nav className="reading-next" aria-label="Continue exploring">{related.length > 0 && <Link href={guide.task.href}>{guide.task.label} <ArrowIcon/></Link>}<Link href="/how-it-works">Understand the complete workflow <ArrowIcon/></Link></nav>
  </main>;
}
